Headings subtotals update
Crunch-io/apidocs-sphinx pull request #14
Opened 2018-01-08 22:52 UTC by jonkeane

Also caught (and rectified) a missing JSON code block from the sphinx conversion.

2018-01-09 13:12 UTC, slobodan-ilic commented on source/feature-guide/feature-analyzing.rst
> +      {
@jonkeane Is this the format that's going to be returned everywhere? Currently in `whaam`, we have multiple cubes, and not a single JSON (that contains more cubes). The reason I'm asking is, obviously, `cr.exporter`, but I also want to be sure what this implicates...

2018-01-23 21:18 UTC, malecki approved these changes

2018-01-23 21:23 UTC, malecki requested changes
isnt' it "function": {"subtotal": not "combine" ? also rebase to master?

2018-01-23 21:43 UTC, malecki approved these changes

2018-01-23 21:43 UTC, merged