Folders 154061511
Crunch-io/apidocs-sphinx pull request #35
Opened 2018-05-04 20:41 UTC by jjdelc

2018-05-04 20:43 UTC, dianaclarke commented on source/feature-guide/feature-folders.rst
> +Variable folders provide a new and faster way to organize
organize... ?

2018-05-04 23:18 UTC, jjdelc commented on source/feature-guide/feature-folders.rst
> +Variable folders provide a new and faster way to organize
:P

2018-05-04 23:20 UTC, jjdelc commented on source/feature-guide/feature-folders.rst
> +Variable folders provide a new and faster way to organize
https://github.com/Crunch-io/apidocs-sphinx/commit/731fc50d0c54e02534b485802b87a19348ebd6b0

2018-05-22 21:23 UTC, digitalresistor requested changes

2018-05-22 21:23 UTC, digitalresistor commented on source/endpoint-reference/endpoint-folders.rst
> +* **Root folder**: The root folder is the top level folder where all other subfolders will be created by dataset editors. All the variables and subfolders here will be public universal for all users
s/varibles/variables/

2018-05-22 21:23 UTC, digitalresistor commented on source/endpoint-reference/endpoint-folders.rst
> +* **Root folder**: The root folder is the top level folder where all other subfolders will be created by dataset editors. All the variables and subfolders here will be public universal for all users
s/public universal/publicly accessible/

2018-05-23 00:00 UTC, jjdelc commented on source/endpoint-reference/endpoint-folders.rst
> +* **Root folder**: The root folder is the top level folder where all other subfolders will be created by dataset editors. All the variables and subfolders here will be public universal for all users
Done, done!

2018-05-23 02:57 UTC, digitalresistor approved these changes

2018-06-01 14:19 UTC, merged